### ISSUE TITLE
aapt2 for arm64(android)

### ISSUE THREAD

**Issue by Barterio** [thejunkjon/android-tools#1]
Hi, do you have a clue how to build an aapt2 for arm64 arch?

**Comment by thejunkjon** [comment]
Hi @Barterio , looking at the build script for aapt2 (below), the process seems to be similar to how I did the original aapt.

https://android.googlesource.com/platform/frameworks/base/+/android-9.0.0_r33/tools/aapt2/Android.bp

Here is the patch file I created for aapt.

https://github.com/thejunkjon/android-tools/blob/master/patch/android-9.0.0_r33/frameworks/base/%2B/tools/aapt/Android.bp.patch

If I have time, I'll try to post the binaries for aapt2 as well.

**Comment by thejunkjon** [comment]
Hi @Barterio, I was able to build aapt2 for arm64.

https://github.com/thejunkjon/android-tools/blob/master/build/android-9.0.0_r33/aapt2/arm64/bin/aapt2

Please give this a try.

**Comment by Barterio** [comment]
Hi @thejunkjon, Thanks for your time and attention for my request. 
I will test it and tell you about results.

Can I contribute somehow to this process?

**Comment by zhangfuwen** [comment]
> Hi @Barterio, I was able to build aapt2 for arm64.
> 
> https://github.com/thejunkjon/android-tools/blob/master/build/android-9.0.0_r33/aapt2/arm64/bin/aapt2
> 
> Please give this a try.

Hi, I am also interested in aapt2 for arm64, I am running android studios on ARM-Linux. Can this binary be run on arm linux?

**Comment by victorwads** [comment]
Hi @JonForShort, i want some help, because projects with newer buildTools version needs a new version of aapt2 and i just found android 9 and 11 aapt2 builded por aarch64/arm64. could you help me?

I`m trying to use my cellphone to setup a Android Development Enviroment on a Snapdragon 8 Gen 1. I sucessuly run Android Studio and Visual Studio Code Server, but i get some problem when using a new version ok build Tools,

**Comment by OliverKoo** [comment]
Can't believe I stumble upon this 🙏 Thank you so much @JonForShort JonForShort 

How do ya'll tell Gradle to use the customize downloaded aapt2 binary? I saw this[ SO post ](https://stackoverflow.com/questions/68814649/is-there-a-way-to-tell-gradle-always-to-use-a-custom-binary-of-aapt2)
but looks like `android.aapt2FromMavenOverride=path to custom aapt2 binary` is deprecated.

**Comment by mopsalarm** [comment]
For Linux users, eg. using ashai or a raspberry pi: 
You can also use qemu to emulate x86_64 binaries on aarch64. If you use binfmt, compiling an app just works, even with aapt2 from maven.
Just register qemu as interpreter for x86_64 binaries like this: https://github.com/tonistiigi/binfmt?tab=readme-ov-file#installing-emulators

And to execute dynamicly linked binaries like aapt2 you might need to install the ld-linux-x86_64.so.2 file from an x86_64 Linux system under /lib64/

**Comment by bogdanHD** [comment]
"404 - page not found". Please provide a new link to the files.

**Comment by SuperCowProducts** [comment]
> "404 - page not found". Please provide a new link to the files.

@bogdanHD the latest should be https://github.com/JonForShort/android-tools/blob/master/build/android-11.0.0_r33/aapt2/arm64-v8a/bin/aapt2, although last commit was 5 years ago
