### ISSUE TITLE
What is the command for the build process?

### ISSUE THREAD

**Issue by anqurvanillapy** [thejunkjon/android-tools#10]
I have some hosts on x86 and aarch64 and try to reproduce your process to build aapt/aapt2 for aarch64 as target, but my AOSP branch is Android-9.0.0-r54.  After patching the build files I get errors when building the tools, and my command are simply:

```bash
$ source build/envsetup.sh
$ lunch aosp_arm64-eng
$ mmm frameworks/base/tools/aapt
$ mmm frameworks/base/tools/aapt2
```

Are the commands correct for a cross-compiling?  Could you provide your commands for the build?

**Comment by anqurvanillapy** [comment]
Well, after some tweaks, I could successfully build the tools just using the commands above.  Thanks for your patches and amazing ideas!

**Comment by nishithkhanna** [comment]
Can you tell about the changes and tweaks you did?

**Comment by anqurvanillapy** [comment]
> Can you tell about the changes and tweaks you did?

IIRC,

1. For Android-9.0.0-r54, there is a C++ bug in `aapt` tool, where there is a class `MultiApkGenerator` missing a virtual destructor.  If there's any compilation error for this, just add one, according to the source location
1. Declaration of the `aapt`'s binary is in `Android.mk`, not in `Android.bp`, and I comment out all the Makefile code of `aapt`, and copy the code from this repo's `Android.bp`, using the `.bp` way for building binaries
1. Manually apply the patches to related `Android.bp`s
1. Move a test directory of `aapt2` out of the AOSP build directory.  I have no idea why it keeps bothering me for unknown errors
```bash
mv frameworks/base/tools/aapt2/integration-tests/ ~/
```
1. Run the build
```bash
$ source build/envsetup.sh
$ lunch aosp_arm64-eng
$ mmm frameworks/base/tools/aapt
$ mmm frameworks/base/tools/aapt2
```

**Comment by nishithkhanna** [comment]
Hey thanks. I was trying to make it for Android  11 r1. Maybe it needs more changes.
