### ISSUE TITLE
Aapt shared library

### ISSUE THREAD

**Issue by timscriptov** [thejunkjon/android-tools#22]
Hello!

Do you have plans to build a library into a **.so**  file?

**Comment by timscriptov** [comment]
New version Aide used **libaapt.so** and **libaidl.so**

**Comment by JonForShort** [comment]
Hi @TimScriptov , yes I can build these into shared libraries for you.  Is this for Android 9 or Android 11?

**Comment by timscriptov** [comment]
@JonForShort please wait, I try libaapt.so v9

**Comment by timscriptov** [comment]
Error:
aapt: aapt exited with code 132

![Screenshot_20210509_103132_com aide ui](https://user-images.githubusercontent.com/31324315/117561659-1fda4e80-b0b2-11eb-9192-fdf43520a9ff.jpg)

**Comment by JonForShort** [comment]
Can you share the error that you got? Is ```exit code 132``` that came from aapt or was this something else?

**Comment by timscriptov** [comment]
@JonForShort Error in aapt.
For normal operation of **libaapt.so** on an android device, you need to comment out the code in the ≈ **Main.cpp and others**, all calls are Sustem.exit(0-3).

There will be time to independently assemble **aapt** based on **android 10**
More info: https://github.com/t-arn/java-ide-droid/blob/master/jni/aapt/README.TXT

**Comment by RohitVermaOP** [comment]
New version Aide not used .so

**Comment by RohitVermaOP** [comment]
- example : Runtime.getRuntime().exec(new String[] {Context#getApplicationInfo().nativeLibraryDir, "--help"});

**Comment by rupeshkumar22** [comment]
I tried running libaapt2.so (arm64-v8a) using `System.load(/data/data/packageName/files/x86/lib/libaapt2.so)` on x86 API 30 AVD Emulator. I get the following Error in logs:
```
java.lang.UnsatisfiedLinkError: dlopen failed: library "libprotobuf-cpp-lite.so" not found: needed by /data/data/packageName/files/x86/lib/libaapt2.so in namespace classloader-namespace
        at java.lang.Runtime.load0(Runtime.java:939)
        at java.lang.System.load(System.java:1628)
```
Maybe [this](https://stackoverflow.com/questions/32688089/how-to-build-libprotobuf-lite-so) is related to it. Any idea on how can I run it inside an app? @JonForShort @TimScriptov 

Thanks

UPDATE:
Resolved [Here](https://github.com/JonForShort/android-tools/issues/25)
