### ISSUE TITLE
Aidl

### ISSUE THREAD

**Issue by timscriptov** [thejunkjon/android-tools#24]
How used aidl binary?

pathToAIDL -I pathTo/framework.aidl pathToFolderAidlFiles

**Comment by JonForShort** [comment]
Hi @TimScriptov , here is an example of how I use it.

https://github.com/JonForShort/android-introspection/blob/master/source/android/vpn/src/main/cpp/aidl/update_aidl.sh#L5

This generates cpp source and headers from the AIDL file.  Is this what you need to do?

**Comment by timscriptov** [comment]
Thx, Need generate aidl to java😅
