### ISSUE TITLE
aapt/aap2 arm64-v8a syntax error

### ISSUE THREAD

**Issue by Frioo** [thejunkjon/android-tools#27]
Hello! First of all, thank you for the builds.
Unfortunately I was unable to run the binaries on my device (Android 11, arm64).
When running `sh aapt` or `sh aapt2`  through adb shell the same error is being thrown: `syntax error: unexpected '('`

**Comment by JonForShort** [comment]
Hi @Frioo , I believe the command you are running will attempt to run the binaries as a shell script which is not correct.  After you push the binaries on your device, can you try the following?

```
chmod +x aapt
./aapt
```

Note that ```chmod``` will make the binaries executable.

**Comment by Frioo** [comment]
Hey, thanks for your response. You were completely right, and I managed to get it working!
One thing worth noting is that I was unable to update permissions for aapt on /sdcard/,
works flawlessly from /data/.
