### ISSUE TITLE
32bit Godot and aapt2 x86

### ISSUE THREAD

**Issue by MiqueiasDevGames** [thejunkjon/android-tools#29]
I'm trying to build a game for android using godot on 32-bit linux, but as google now only accepts app.aab upload, I'm having a problem with aapt2 which only supports 64-bit. Could I use your aapt2 x86 on linux for this purpose?

**Comment by JonForShort** [comment]
HI @miqueias9889, unfortunately this is not possible.  The binaries in this repository have been compiled against the android tool chain which means they can only run on android devices.  If you want to run ```aapt2``` on 32-bit linux, you should be able to get the binaries from the official Android command line tools (https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip).  Hope this helps!
