### ISSUE TITLE
Hi jon! I have a query..

### ISSUE THREAD

**Issue by rupesh-kumar-lpu** [thejunkjon/android-tools#6]
I execute bin/binaries, it executes successfully. But I want to know is it necessary to load .so file by system.loadlibrary(). Does it make any difference as the binary is able to execute without loading lib/.so file. I am executing bin/aapt_binaries on android.
Thank You!
Rupesh

**Comment by thejunkjon** [comment]
Hi @rupesh-kumar-lpu, the binaries do not need to be loaded using the `System.loadLibrary()`.  The executables have the code statically linked in them so they can be run independently.

At some point, I would like to put more effort into this project (refresh all the binaries, provide sample code, add documentation, etc.) but I've been too busy.  I'll try to get back to this when things are no longer so hectic.

**Comment by rupesh-kumar-lpu** [comment]
Thank you for your reply @thejunkjon , Binaries are really helpful and it is exactly what I was looking for...
Happy Coding!
Rupesh Kumar
